version : "3.8"

services:
  agendador_tarefas:
    build: .
    container_name: agendador_tarefas
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATA_MONGODB_URI= mongodb://mongo:27017/db_agendador
    depends_on:
      - mongo
  bff_agendador:
    build: .
    container_name: bff_agendador
    ports:
      - "8083:8083"
    environment:
      - USUARIO_URL:usuario:8080/usuario
      - AGENDADOR_TAREFAS_URL=agendador_tarefas:8081/tarefas
      - NOTIFICACAO_URL=notificacao:8082/email
  usuario:
    build: .
    container_name: usuario
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/db_usuario
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
    depends_on:
      - postgres
  notificacao:
    build: .
    container_name: notificacao
    ports:
      - "8084:8084"
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: no
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD : admin
      POSTGRES_DB: db_usuarioo
    ports:
      - "5433:5432"
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: no
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: db_agendador
networks:
  default:
    driver: bridge